AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an S3 bucket

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-bucket'
      AccessControl: Private

Outputs:
  BucketName:
    Description: The name of the S3 bucket
    Value: !Ref S3Bucket
